### ISSUE TITLE
Iterators as subsets should be supported

### ISSUE THREAD

**Issue by ostrolucky** [bpolaszek/cartesian-product#1]
Hey, I've run into your useful library and as far as I see it's the only one that does cartesian products while preserving string keys. However, it does not support Iterator as subsets, because of this exception being thrown https://github.com/bpolaszek/cartesian-product/blob/af1d65e5b7712fdf799d3379eba539b6dae7f5e9/src/CartesianProduct.php#L67

My use case is to do cartesian product of two mongodb cursors.

**Comment by bpolaszek** [comment]
I'm not against it, but the iterator must be countable in order to match with the `count` method. Would you mind opening a PR for this?

**Comment by ostrolucky** [comment]
I was hoping you will just delete the method. Code contributions are subject of personal code style and I don't want having to come back to it and rework it.

**Comment by bpolaszek** [comment]
Validation is needed to ensure the object to work properly. I'll try to give a try to Iterators in a few days.

**Comment by ostrolucky** [comment]
not sure how useful is exception being thrown over normal php error though. There isn't much value for explicit, manual if there, result is same
