### ISSUE TITLE
Add benchmark to README

### ISSUE THREAD

**Issue by PatchRanger** [bpolaszek/cartesian-product#3]
I've created a benchmark in order to compare my own cartesian iterator implementation with others, including yours: https://github.com/PatchRanger/php-cartesian-benchmark . It looks like your library is the best in all cases except the last synthetic one. I believe you may want to add the link to the benchmark to README in order to convince to use your library. Up to you.

**Comment by bpolaszek** [comment]
Hello @PatchRanger, thank you very much! It's on its way.
